name: active_visium
channels:
  - pytorch
  - https://repo.anaconda.cloud/repo/main
  - conda-forge
  - nvidia
  - rapidsai
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - backcall=0.2.0
  - blas=1.0
  - bottleneck=1.3.5
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2023.01.10
  - cairo=1.16.0
  - certifi=2022.12.7
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - contourpy=1.0.5
  - cryptography=39.0.1
  - cuda-cudart=11.7.99
  - cuda-cupti=11.7.101
  - cuda-libraries=11.7.1
  - cuda-nvrtc=11.7.99
  - cuda-nvtx=11.7.91
  - cuda-runtime=11.7.1
  - cycler=0.11.0
  - dbus=1.13.18
  - debugpy=1.5.1
  - decorator=5.1.1
  - expat=2.4.9
  - ffmpeg=4.3
  - filelock=3.9.0
  - fontconfig=2.14.1
  - fonttools=4.25.0
  - freetype=2.12.1
  - gdk-pixbuf=2.42.10
  - giflib=5.2.1
  - glib=2.69.1
  - gmp=6.2.1
  - gmpy2=2.1.2
  - gnutls=3.6.15
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - icu=58.2
  - idna=3.4
  - importlib-metadata=6.0.0
  - importlib_metadata=6.0.0
  - importlib_resources=5.2.0
  - intel-openmp=2023.1.0
  - jinja2=3.1.2
  - jpeg=9e
  - jupyter_core=5.3.0
  - kiwisolver=1.4.4
  - krb5=1.19.4
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libclang=10.0.1
  - libcublas=11.10.3.66
  - libcufft=10.7.2.124
  - libcufile=1.6.1.9
  - libcurand=10.3.2.106
  - libcusolver=11.4.0.1
  - libcusparse=11.7.4.91
  - libdeflate=1.17
  - libedit=3.1.20221030
  - libevent=2.1.12
  - libffi=3.4.2
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libiconv=1.16
  - libidn2=2.3.2
  - libllvm10=10.0.1
  - libnpp=11.7.4.75
  - libnvjpeg=11.8.0.2
  - libpng=1.6.39
  - libpq=12.9
  - libsodium=1.0.18
  - libstdcxx-ng=11.2.0
  - libtasn1=4.19.0
  - libtiff=4.2.0
  - libunistring=0.9.10
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxcb=1.15
  - libxkbcommon=1.0.1
  - libxml2=2.9.14
  - libxslt=1.1.35
  - lz4-c=1.9.4
  - markupsafe=2.1.1
  - matplotlib=3.7.1
  - matplotlib-base=3.7.1
  - matplotlib-inline=0.1.6
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.6
  - mkl_random=1.2.2
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpmath=1.2.1
  - munkres=1.1.4
  - ncurses=6.4
  - nest-asyncio=1.5.6
  - nettle=3.7.3
  - networkx=2.8.4
  - nspr=4.33
  - nss=3.74
  - numexpr=2.8.4
  - numpy=1.24.3
  - numpy-base=1.24.3
  - openh264=2.1.1
  - openjpeg=2.3.1
  - openslide=3.4.1
  - openssl=1.1.1t
  - packaging=23.0
  - pandas=1.5.3
  - parso=0.8.3
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.4.0
  - pip=23.0.1
  - pixman=0.40.0
  - ply=3.11
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.15.1
  - pyopenssl=23.0.0
  - pyparsing=3.0.9
  - pyqt=5.15.7
  - pyqt5-sip=12.11.0
  - pysocks=1.7.1
  - python=3.9.16
  - python-dateutil=2.8.2
  - pytorch-cuda=11.7
  - pytorch-mutex=1.0
  - pytz=2022.7
  - pyzmq=25.0.2
  - qt-main=5.15.2
  - qt-webengine=5.15.9
  - qtwebkit=5.212
  - readline=8.2
  - requests=2.29.0
  - setuptools=66.0.0
  - sip=6.6.2
  - six=1.16.0
  - sqlite=3.41.2
  - sympy=1.11.1
  - tbb=2021.8.0
  - tk=8.6.12
  - toml=0.10.2
  - tqdm=4.65.0
  - tzdata=2023c
  - urllib3=1.26.15
  - wheel=0.38.4
  - xz=5.4.2
  - zeromq=4.3.4
  - zipp=3.11.0
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
    - access==1.1.9
    - ace-tools==0.0
    - aenum==3.1.15
    - affine==2.4.0
    - aiohappyeyeballs==2.4.2
    - aiohttp==3.10.8
    - aiosignal==1.3.1
    - albumentations==1.3.0
    - anndata==0.9.1
    - annotated-types==0.7.0
    - antlr4-python3-runtime==4.9.3
    - appdirs==1.4.4
    - archetypes==0.4.2
    - asttokens==2.2.1
    - async-timeout==4.0.3
    - attrs==23.1.0
    - beautifulsoup4==4.12.2
    - bleach==6.2.0
    - chardet==4.0.0
    - click==8.1.3
    - click-plugins==1.1.1
    - cligj==0.7.2
    - cmake==3.26.3
    - comm==0.2.2
    - defusedxml==0.7.1
    - deprecation==2.1.0
    - docker-pycreds==0.4.0
    - docopt==0.6.2
    - esda==2.4.3
    - executing==1.2.0
    - fastjsonschema==2.21.1
    - fiona==1.9.4.post1
    - frozenlist==1.4.1
    - fsspec==2024.3.1
    - geopandas==0.13.0
    - get-annotations==0.1.2
    - giddy==2.3.4
    - gitdb==4.0.10
    - gitpython==3.1.32
    - h5py==3.8.0
    - harmonypy==0.0.10
    - huggingface-hub==0.22.2
    - hydra-core==1.3.2
    - igraph==0.10.4
    - imageio==2.30.0
    - inequality==1.0.0
    - ipykernel==5.3.4
    - ipython==8.12.3
    - ipython-genutils==0.2.0
    - ipywidgets==8.1.2
    - jedi==0.18.2
    - joblib==1.2.0
    - jsonschema==4.23.0
    - jsonschema-specifications==2024.10.1
    - jupyter-client==6.1.12
    - jupyterlab-pygments==0.3.0
    - jupyterlab-widgets==3.0.10
    - lazy-loader==0.2
    - legacy-api-wrap==1.4
    - leidenalg==0.9.1
    - libpysal==4.7.0
    - lightly==1.5.13
    - lightly-utils==0.0.2
    - lightning-utilities==0.11.7
    - lit==16.0.5.post0
    - llvmlite==0.40.0
    - mapclassify==2.5.0
    - mgwr==2.1.2
    - mistune==3.1.1
    - momepy==0.6.0
    - multidict==6.1.0
    - natsort==8.3.1
    - nbclient==0.10.2
    - nbconvert==7.16.6
    - nbformat==5.10.4
    - numba==0.57.0
    - nvidia-cublas-cu11==11.10.3.66
    - nvidia-cublas-cu12==12.1.3.1
    - nvidia-cuda-cupti-cu11==11.7.101
    - nvidia-cuda-cupti-cu12==12.1.105
    - nvidia-cuda-nvrtc-cu11==11.7.99
    - nvidia-cuda-nvrtc-cu12==12.1.105
    - nvidia-cuda-runtime-cu11==11.7.99
    - nvidia-cuda-runtime-cu12==12.1.105
    - nvidia-cudnn-cu11==8.5.0.96
    - nvidia-cudnn-cu12==9.1.0.70
    - nvidia-cufft-cu11==10.9.0.58
    - nvidia-cufft-cu12==11.0.2.54
    - nvidia-curand-cu11==10.2.10.91
    - nvidia-curand-cu12==10.3.2.106
    - nvidia-cusolver-cu11==11.4.0.1
    - nvidia-cusolver-cu12==11.4.5.107
    - nvidia-cusparse-cu11==11.7.4.91
    - nvidia-cusparse-cu12==12.1.0.106
    - nvidia-nccl-cu11==2.14.3
    - nvidia-nccl-cu12==2.20.5
    - nvidia-nvjitlink-cu12==12.6.68
    - nvidia-nvtx-cu11==11.7.91
    - nvidia-nvtx-cu12==12.1.105
    - omegaconf==2.3.0
    - opencv-contrib-python==4.5.5.62
    - opencv-python==4.7.0.72
    - opencv-python-headless==4.10.0.84
    - openslide-python==1.2.0
    - pandocfilters==1.5.1
    - pathtools==0.1.2
    - patsy==0.5.3
    - pipreqs==0.5.0
    - platformdirs==3.5.1
    - pointpats==2.3.0
    - prompt-toolkit==3.0.38
    - protobuf==4.24.0
    - pulp==2.7.0
    - pydantic==2.9.2
    - pydantic-core==2.23.4
    - pynndescent==0.5.10
    - pyproj==3.5.0
    - pysal==23.1
    - python-igraph==0.10.4
    - pytorch-lightning==2.4.0
    - pywavelets==1.4.1
    - pyyaml==6.0
    - quantecon==0.7.1
    - qudida==0.0.4
    - rasterio==1.3.7
    - rasterstats==0.19.0
    - referencing==0.36.2
    - rpds-py==0.22.3
    - rtree==1.0.1
    - safetensors==0.4.2
    - scanpy==1.9.3
    - scikit-image==0.20.0
    - scikit-learn==1.2.2
    - scipy==1.9.1
    - seaborn==0.13.2
    - segregation==2.4.2
    - sentry-sdk==2.19.0
    - session-info==1.0.0
    - setproctitle==1.3.2
    - shapely==2.0.1
    - simplejson==3.19.1
    - smmap==5.0.0
    - snuggs==1.4.7
    - soupsieve==2.4.1
    - spaghetti==1.7.3
    - spglm==1.0.8
    - spint==1.0.7
    - splot==1.1.5.post1
    - spopt==0.5.0
    - spreg==1.3.2
    - spvcm==0.3.0
    - stack-data==0.6.2
    - statsmodels==0.14.0
    - stdlib-list==0.8.0
    - tabulate==0.9.0
    - texttable==1.6.7
    - threadpoolctl==3.1.0
    - tifffile==2023.4.12
    - timm==0.9.16
    - tinycss2==1.4.0
    - tobler==0.10
    - torch==2.4.1
    - torchmetrics==1.4.2
    - torchsummary==1.5.1
    - torchvision==0.19.1
    - tornado==6.3.2
    - traitlets==5.9.0
    - triton==3.0.0
    - typing-extensions==4.12.2
    - umap-learn==0.5.3
    - wandb==0.18.7
    - wcwidth==0.2.6
    - webencodings==0.5.1
    - widgetsnbextension==4.0.10
    - wrapt==1.16.0
    - yarg==0.1.9
    - yarl==1.13.1
